apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tylt-edit
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: edit.NAMESPACE_VAR.kubernetes.thetylt.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tylt-ruby
          servicePort: 80
          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tylt-web-node
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: tyl-web-node.NAMESPACE_VAR.kubernetes.thetylt.com
    http:
      paths:
          - path: /
            backend:
              serviceName: tylt-web-node-varnish
              servicePort: 80
          - path: /feed.rss
            backend:
              serviceName: tylt-ruby-varnish
              servicePort: 80
          - path: /feed.atom
            backend:
              serviceName: tylt-ruby-varnish
              servicePort: 80
          - path: /ia.rss
            backend:
              serviceName: tylt-ruby-varnish
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tylt-api
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: api.NAMESPACE_VAR.kubernetes.thetylt.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tylt-ruby-varnish
          servicePort: 80
          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tylt-vote
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: NAMESPACE_VAR.kubernetes.tylt.vote
    http:
      paths:
      - path: /
        backend:
          serviceName: tylt-ruby-varnish
          servicePort: 80
          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tylt-NAMESPACE_VAR
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: NAMESPACE_VAR.kubernetes.thetylt.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tylt-ruby-varnish
          servicePort: 80
      - path: /socket.io
        backend:
          serviceName: tylt-pusher-node
          servicePort: 80
