apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: patroni
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.priority: 10 
spec:
  rules:
  - host: patroni.NAMESPACE_VAR.kubernetes.thetylt.com
    http:
      paths:
      - path: /
        backend:
          serviceName: patroni
          servicePort: 5050
