apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb
spec:
  replicas: 1
  # Must match RETHINKDB-CLUSTER env and service name.
  serviceName: rethinkdb
  template:
    metadata:
      labels:
        db: rethinkdb
        role: replica
    spec:
      containers:

      #RethinkDB container
      - args:
        - --directory
        - /data/db
        - --bind
        - all
        - --cache-size
        - "100"
        env:
        - name: RETHINK_CLUSTER_SERVICE
          value: rethinkdb-cluster
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: codylundquist/helm-rethinkdb-cluster:0.1.0
        livenessProbe:
          exec:
            command:
            - /rethinkdb-probe
        name: rethinkdb-cluster
        ports:
        - containerPort: 29015
          name: cluster
        readinessProbe:
          exec:
            command:
            - /rethinkdb-probe
        volumeMounts:
        - mountPath: /data
          name: datadir

      #RethinkDB python sidecar
      - image: python 
        imagePullPolicy: Always
        name: rethinkdb-sidecar
        command: 
        - /bin/sh
        - -ec
        - |
          pip install rethinkdb -v 
          /usr/local/bin/rethinkdb-restore /mnt/tylt-rethink-prod/${RT_BACKUP_FILE}.tar.gz --force 
        envFrom:
        - configMapRef:
            name: globalvalues
        volumeMounts:
        - name: backup-dir
          mountPath: /mnt/tylt-rethink-prod
          readOnly: PRODUCTION_VAR

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: datadir
        emptyDir: {}
      - name: backup-dir
        hostPath:
          path: /mnt/s3-backup-share/tylt-rethink-prod
