---
apiVersion: v1
kind: Service
metadata:
  name: rethinkdb
  annotations:
    traefik.backend.loadbalancer.sticky: true
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: admin
  - port: 29015
    name: cluster
  - port: 28015
    name: driver
  selector:
    app: rethinkdb
