---
apiVersion: v1
kind: Service
metadata:
  name: rethinkdb
  annotations:
    traefik.backend.loadbalancer.sticky: true
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: admin
  - port: 29015
    targetPort: cluster 
  - port: 28015
    targetPort: driver
  selector:
    app: rethinkdb
