---
apiVersion: v1
kind: Service
metadata:
  name: rethinkdb
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: admin
    name: admin
  - port: 29015
    targetPort: cluster
    name: cluster 
  - port: 28015
    targetPort: driver
    name: driver
  selector:
    app: rethinkdb
