apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: rethinkdb
  name: rethinkdb
spec:
  replicas: 1
  serviceName: rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb 
    spec:
      containers:

      #RethinkDB statefulset
      - image: rosskukulinski/rethinkdb-kubernetes:2.3.5
        imagePullPolicy: Always
        name: rethinkdb
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: RETHINK_CLUSTER
          value: rethinkdb
        - name: USE_SERVICE_LOOKUP
          value: "yes"
        ports:
        - containerPort: 8080
          name: admin
        - containerPort: 28015
          name: driver
        - containerPort: 29015
          name: cluster
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /data
          name: data
        readinessProbe:
          exec:
            command:
            - /probe
        livenessProbe:
          exec:
            command:
              - /probe

      #RethinkDB sidecar
      - image: node
        imagePullPolicy: Always
        name: rethinkdb-sidecar
        command:
        - /bin/bash
        - -ec
        - |
          npm install -g recli
          sleep 30
          recli --host localhost --port 28015 --database tyltInbox 'r.tableCreate("messages_twitter")' 2&>1 || echo $?
          recli --host localhost --port 28015 --database tyltInbox 'r.tableCreate("messages_facebook")' 2&>1 || echo $?
          recli --host localhost --port 28015 --database tyltInbox 'r.tableCreate("polls_facebook")' 2&>1 || echo $?
          recli --host localhost --port 28015 --database tyltInbox 'r.tableCreate("manual_votes")' 2&>1 || echo $?
          while 1 -eq 1; do sleep 10; done
        envFrom:
        - configMapRef:
            name: globalvalues
        volumeMounts:
        - name: backup-dir
          mountPath: /mnt/tylt-rethink-prod
          readOnly: PRODUCTION_VAR

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: data
        emptyDir: {}
      - name: backup-dir
        hostPath:
          path: /mnt/s3-backup-share/tylt-rethink-prod
