apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: rethinkdb
  name: rethinkdb
spec:
  replicas: 1
  serviceName: rethinkdb
  template:
    metadata:
      labels:
        app: rethinkdb 
    spec:
      containers:

      #RethinkDB statefulset
      - image: rosskukulinski/rethinkdb-kubernetes:2.3.5
        imagePullPolicy: Always
        name: rethinkdb
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: RETHINK_CLUSTER
          value: rethinkdb
        - name: USE_SERVICE_LOOKUP
          value: "yes"
        ports:
        - containerPort: 8080
          name: admin
        - containerPort: 28015
          name: driver
        - containerPort: 29015
          name: cluster
        volumeMounts:
        - mountPath: /data
          name: data
        readinessProbe:
          exec:
            command:
            - /probe
        livenessProbe:
          exec:
            command:
              - /probe

      #RethinkDB node sidecar
      - image: python
        imagePullPolicy: Always
        name: rethinkdb-sidecar
        command:
        - /bin/sh
        - -ec
        - |
          pip install rethinkdb
          LATEST_DUMP=$(ls -Art /mnt/tylt-rethink-prod/*.tar.gz | tail -n1)
          /usr/local/bin/rethinkdb-restore $LATEST_DUMP -c localhost:28015 --clients 16 || echo "Restore Failed"
          while [ 1 -eq 1 ]; do sleep 10; done
        envFrom:
        - configMapRef:
            name: globalvalues
        volumeMounts:
        - name: backup-dir
          mountPath: /mnt/tylt-rethink-prod
          readOnly: PRODUCTION_VAR
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - |
              ! pgrep -f "/usr/local/bin/python /usr/local/bin/rethinkdb-restore"
          initialDelaySeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: data
        emptyDir: {}
      - name: backup-dir
        hostPath:
          path: /mnt/s3-backup-share/tylt-rethink-prod
